apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredimagestags
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredImagesTags
      validation:
        openAPIV3Schema:
          type: object
          properties:
            images:
              type: array
              items:
                type: string
  targets:
     - target: admission.k8s.gatekeeper.sh
       rego: |
          package k8srequiredimagestags
          violation[{"msg": msg}]{

          msg:=sprintf("Some example")
          }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredImagesTags
metadata:
  name: image-tag-constraints
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pods"]
  parameters:
    images:
      - latest
      - stable
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-check-constrain
  labels:
    name: pod-check-constrain
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
