apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredimagestags
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredImagesTags
      validation:
        openAPIV3Schema:
          type: object
          properties:
            images:
              type: array
              items:
                type: string
  targets:
     - target: admission.k8s.gatekeeper.sh
       rego: |
          package k8srequiredimagestags
          violation[{"msg": "hello"}]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredImagesTags
metadata:
  name: image-tag-constraints
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pods"]
    parameters:
      images:
        - latest
        - stable   
