apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenyname
spec:
  crd:
    spec:
      names:
        kind: K8sDenyName
      validation:
        openAPIV3Schema:
          properties:
            invalidName:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
            package k8sdenyname
            violation[{"msg": msg}]{
            input.review.operation="CREATE"
            input.review.objects.metadata.name == input.parameters.invalidName
            msg := sprintf("Name %v is not allowed", [input.parameters.invalidName])
            }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyName
metadata:
  name: no-policy-validation
spec:
  parameters:
    invalidName: "policy-validation"
---
apiVersion: v1
kind: Pod
metadata:
  name: "policy-validation"
spec:
  containers:
  - image: nginx
    name: nginx
